'use client';

import ModalContextProvider from '@/context/ModalContext';
import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

const font = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Habit tracker app',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={font.className + ' bg-neutral-50 flex justify-center items-center'}>
				<ModalContextProvider>
					{children}
				</ModalContextProvider>
			</body>
		</html>
	)
}
