import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { AuthContextProvider } from '@/context/AuthContext';
import { NotificationContextProvider } from '@/context/NotificationContext';

const font = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Habit tracker app',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={font.className}>
				<NotificationContextProvider>
					<AuthContextProvider>
						{children}
					</AuthContextProvider>
				</NotificationContextProvider>
			</body>
		</html>
	)
}
